"""Render the single allowed OS package step from packaging/inputs.json (os_security_upgrades).

Dockerfiles must contain exactly this text (test_supply_chain checks it), so the only apt use is an
exact-version upgrade from a fixed, signature-checked Debian security snapshot; base sources unused.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render(inputs=None):
    spec = (inputs or json.loads((ROOT / 'packaging/inputs.json').read_text()))['os_security_upgrades']
    pins = ' '.join('%s=%s' % kv for kv in sorted(spec['packages'].items()))
    checks = ' \\\n && '.join('test "$(dpkg-query -W -f=\'${Version}\' %s)" = "%s"' % kv for kv in sorted(spec['packages'].items()))
    src = ("deb [signed-by=/usr/share/keyrings/debian-archive-keyring.gpg check-valid-until=no] "
           "http://snapshot.debian.org/archive/debian-security/%s %s main" % (spec['snapshot'], spec['suite']))
    opts = '-o Dir::Etc::SourceList=/tmp/woow-security.list -o Dir::Etc::SourceParts=/tmp/woow-apt-parts'
    return ('# Generated by packaging/os_upgrades.py from inputs.json os_security_upgrades: exact-version\n'
            '# upgrades from a fixed debian-security snapshot only (base sources unused). Remove when the base has them.\n'
            'RUN mkdir /tmp/woow-apt-parts \\\n'
            " && echo '%s' > /tmp/woow-security.list \\\n"
            ' && apt-get %s update \\\n'
            ' && apt-get %s install -y --no-install-recommends --only-upgrade %s \\\n'
            ' && rm -rf /var/lib/apt/lists/* /tmp/woow-security.list /tmp/woow-apt-parts \\\n'
            ' && %s\n') % (src, opts, opts, pins, checks)


if __name__ == '__main__':
    print(render(), end='')
